export const SET_DATE = 'SET_DATE';

export const OPEN_DIALOG_WINDOW = 'OPEN_DIALOG_WINDOW';
export const CLOSE_DIALOG_WINDOW = 'CLOSE_DIALOG_WINDOW';

export const SELECT_LESSON = 'SELECT_LESSON';

export const SET_HEADER = 'SET_HEADER';

export const UPDATE_RESCHEDULE = 'UPDATE_RESCHEDULE';
export const CLEAR_RESCHEDULE = 'CLEAR_RESCHEDULE';
