export const SET_DATE = 'SET_DATE';

export const OPEN_DIALOG_WINDOW = 'OPEN_DIALOG_WINDOW';
export const CLOSE_DIALOG_WINDOW = 'CLOSE_DIALOG_WINDOW';

export const SELECT_CLASSROOM = 'SELECT_CLASSROOM';
export const EDIT_CLASSROOM = 'EDIT_CLASSROOM';
export const OCCUPY_CLASSROOM = 'OCCUPY_CLASSROOM';

export const SELECT_LESSON = 'SELECT_LESSON';
