export const GET_FACULTIES_FETCH = 'GET_FACULTIES_FETCH';
export const GET_FACULTIES_REQUEST = 'GET_FACULTIES_REQUEST';
export const GET_FACULTIES_SUCCESS = 'GET_FACULTIES_SUCCESS';
export const GET_FACULTIES_FAIL = 'GET_FACULTIES_FAIL';
