export const GET_COURSES_FETCH = 'GET_COURSES_FETCH';
export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';

export const CLEAR_COURSES = 'CLEAR_COURSES';
