export const GET_GROUPS_FETCH = 'GET_GROUPS_FETCH';
export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAIL = 'GET_GROUPS_FAIL';

export const SELECT_GROUP = 'SELECT_GROUP';

export const SET_GROUPS = 'SET_GROUPS';
