export const GET_CLASSROOMS_FETCH = 'GET_CLASSROOMS_FETCH';
export const GET_CLASSROOMS_REQUEST = 'GET_CLASSROOMS_REQUEST';
export const GET_CLASSROOMS_SUCCESS = 'GET_CLASSROOMS_SUCCESS';
export const GET_CLASSROOMS_FAIL = 'GET_CLASSROOMS_FAIL';

export const GET_CLASSROOM_FETCH = 'GET_CLASSROOM_FETCH';
export const GET_CLASSROOM_REQUEST = 'GET_CLASSROOM_REQUEST';
export const GET_CLASSROOM_SUCCESS = 'GET_CLASSROOM_SUCCESS';
export const GET_CLASSROOM_FAIL = 'GET_CLASSROOM_FAIL';

export const DELETE_CLASSROOM_FETCH = 'DELETE_CLASSROOM_FETCH';
export const DELETE_CLASSROOM_REQUEST = 'DELETE_CLASSROOM_REQUEST';
export const DELETE_CLASSROOM_SUCCESS = 'DELETE_CLASSROOM_SUCCESS';
export const DELETE_CLASSROOM_FAIL = 'DELETE_CLASSROOM_FAIL';

export const UPDATE_CLASSROOM_FETCH = 'UPDATE_CLASSROOM_FETCH';
export const UPDATE_CLASSROOM_REQUEST = 'UPDATE_CLASSROOM_REQUEST';
export const UPDATE_CLASSROOM_SUCCESS = 'UPDATE_CLASSROOM_SUCCESS';
export const UPDATE_CLASSROOM_FAIL = 'UPDATE_CLASSROOM_FAIL';

export const GET_CLASSROOM_WITH_EVENTS_FETCH = 'GET_CLASSROOM_WITH_EVENTS_FETCH';
export const GET_CLASSROOM_WITH_EVENTS_REQUEST = 'GET_CLASSROOM_WITH_EVENTS_REQUEST';
export const GET_CLASSROOM_WITH_EVENTS_SUCCESS = 'GET_CLASSROOM_WITH_EVENTS_SUCCESS';
export const GET_CLASSROOM_WITH_EVENTS_FAIL = 'GET_CLASSROOM_WITH_EVENTS_FAIL';

export const CLEAR_CLASSROOMS = 'CLEAR_CLASSROOMS';
export const CLEAR_CLASSROOM = 'CLEAR_CLASSROOM';
