export const AUTHORIZE_FETCH = 'AUTHORIZE_FETCH';
export const AUTHORIZE_REQUEST = 'AUTHORIZE_REQUEST';
export const AUTHORIZE_SUCCESS = 'AUTHORIZE_SUCCESS';
export const AUTHORIZE_FAIL = 'AUTHORIZE_FAIL';

export const REGISTER_FETCH = 'REGISTER_FETCH';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CHECK_AUTH_FETCH = 'CHECK_AUTH_FETCH';
export const CHECK_USER_FETCH = 'CHECK_USER_FETCH';
export const WHO_AM_I_REQUEST = 'WHO_AM_I_REQUEST';
export const WHO_AM_I_SUCCESS = 'WHO_AM_I_SUCCESS';
export const WHO_AM_I_FAIL = 'WHO_AM_I_FAIL';

export const LOGOUT_FETCH = 'LOGOUT_FETCH';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';
