export const GET_LECTURERS_FETCH = 'GET_LECTURERS_FETCH';
export const GET_LECTURERS_REQUEST = 'GET_LECTURERS_REQUEST';
export const GET_LECTURERS_SUCCESS = 'GET_LECTURERS_SUCCESS';
export const GET_LECTURERS_FAIL = 'GET_LECTURERS_FAIL';
