export const GET_TIME_BLOCKS_FETCH = 'GET_TIME_BLOCKS_FETCH';
export const GET_TIME_BLOCKS_REQUEST = 'GET_TIME_BLOCKS_REQUEST';
export const GET_TIME_BLOCKS_SUCCESS = 'GET_TIME_BLOCKS_SUCCESS';
export const GET_TIME_BLOCKS_FAIL = 'GET_TIME_BLOCKS_FAIL';
