export const UPDATE_EVENT = 'UPDATE_EVENT';
export const CLEAR_EVENT = 'CLEAR_EVENT';
export const CHANGE_IS_FREE = 'CHANGE_IS_FREE';

export const CREATE_EVENT_FETCH = 'CREATE_EVENT_FETCH';
export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';

export const DELETE_EVENT_FETCH = 'DELETE_EVENT_FETCH';
export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';

export const SELECT_TIME = 'SELECT_TIME';

export const GET_EVENT_FETCH = 'GET_EVENT_FETCH';
export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAIL = 'GET_EVENT_FAIL';
