export const GET_DISCIPLINES_FETCH = 'GET_DISCIPLINES_FETCH';
export const GET_DISCIPLINES_REQUEST = 'GET_DISCIPLINES_REQUEST';
export const GET_DISCIPLINES_SUCCESS = 'GET_DISCIPLINES_SUCCESS';
export const GET_DISCIPLINES_FAIL = 'GET_DISCIPLINES_FAIL';
