export const GET_BUILDINGS_FETCH = 'GET_BUILDINGS_FETCH';
export const GET_BUILDINGS_REQUEST = 'GET_BUILDINGS_REQUEST';
export const GET_BUILDINGS_SUCCESS = 'GET_BUILDINGS_SUCCESS';
export const GET_BUILDINGS_FAIL = 'GET_BUILDINGS_FAIL';

export const SELECT_BUILDING = 'SELECT_BUILDING';
