export const GET_SCHEDULE_FETCH = 'GET_SCHEDULE_FETCH';
export const GET_SCHEDULE_REQUEST = 'GET_SCHEDULE_REQUEST';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE_FAIL = 'GET_SCHEDULE_FAIL';

export const GET_LESSON_FETCH = 'GET_LESSON_FETCH';
export const GET_LESSON_REQUEST = 'GET_LESSON_REQUEST';
export const GET_LESSON_SUCCESS = 'GET_LESSON_SUCCESS';
export const GET_LESSON_FAIL = 'GET_LESSON_FAIL';

export const CLEAR_SCHEDULE = 'CLEAR_SCHEDULE';

export const UPDATE_SCHEDULE_TYPE = 'UPDATE_SCHEDULE_TYPE';

export const EDIT_SCHEDULE_FETCH = 'EDIT_SCHEDULE_FETCH';
export const EDIT_SCHEDULE_REQUEST = 'EDIT_SCHEDULE_REQUEST';
export const EDIT_SCHEDULE_SUCCESS = 'EDIT_SCHEDULE_SUCCESS';
export const EDIT_SCHEDULE_FAIL = 'EDIT_SCHEDULE_FAIL';

export const CREATE_SCHEDULE_ITEM_FETCH = 'CREATE_SCHEDULE_ITEM_FETCH';
export const CREATE_SCHEDULE_ITEM_REQUEST = 'CREATE_SCHEDULE_ITEM_REQUEST';
export const CREATE_SCHEDULE_ITEM_SUCCESS = 'CREATE_SCHEDULE_ITEM_SUCCESS';
export const CREATE_SCHEDULE_ITEM_FAIL = 'CREATE_SCHEDULE_ITEM_FAIL';

export const DELETE_SCHEDULE_ITEM_FETCH = 'DELETE_SCHEDULE_ITEM_FETCH';
export const DELETE_SCHEDULE_ITEM_REQUEST = 'DELETE_SCHEDULE_ITEM_REQUEST';
export const DELETE_SCHEDULE_ITEM_SUCCESS = 'DELETE_SCHEDULE_ITEM_SUCCESS';
export const DELETE_SCHEDULE_ITEM_FAIL = 'DELETE_SCHEDULE_ITEM_FAIL';

export const EDIT_SCHEDULE_ITEM_FETCH = 'EDIT_SCHEDULE_ITEM_FETCH';
export const EDIT_SCHEDULE_ITEM_REQUEST = 'EDIT_SCHEDULE_ITEM_REQUEST';
export const EDIT_SCHEDULE_ITEM_SUCCESS = 'EDIT_SCHEDULE_ITEM_SUCCESS';
export const EDIT_SCHEDULE_ITEM_FAIL = 'EDIT_SCHEDULE_ITEM_FAIL';

export const SELECT_SCHEDULE_ITEM = 'SELECT_SCHEDULE_ITEM';
export const CLEAR_SCHEDULE_ITEM = 'CLEAR_SCHEDULE_ITEM';
