export const GET_SCHEDULE_FETCH = 'GET_SCHEDULE_FETCH';
export const GET_SCHEDULE_REQUEST = 'GET_SCHEDULE_REQUEST';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE_FAIL = 'GET_SCHEDULE_FAIL';

export const GET_LESSON_FETCH = 'GET_LESSON_FETCH';
export const GET_LESSON_REQUEST = 'GET_LESSON_REQUEST';
export const GET_LESSON_SUCCESS = 'GET_LESSON_SUCCESS';
export const GET_LESSON_FAIL = 'GET_LESSON_FAIL';

export const CLEAR_SCHEDULE = 'CLEAR_SCHEDULE';

export const UPDATE_SCHEDULE_TYPE = 'UPDATE_SCHEDULE_TYPE';
